# Generated by Django 4.1.1 on 2022-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloOficina',
            fields=[
                ('numero_articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoComputacional',
            fields=[
                ('numero_insumo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('marca', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('perfil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('numero_chasis', models.CharField(max_length=17, unique=True)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('ultima_revision', models.DateField()),
                ('proxima_revision', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
