# Generated by Django 4.1.1 on 2022-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdministracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
